costmap:
  costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 20.0
      publish_frequency: 20.0
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.5
      rolling_window: true
      width: 30
      height: 30
      resolution: 0.05
      footprint: "[[1.2, 0.825], [1.2, -0.825], [-1.2, -0.825], [-1.2, 0.825]]"
      footprint_padding: 0.05
      track_unknown_space: false
      plugins: ["static_layer", "projected_static_layer", "local_obstacle_layer", "actor_obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /map
        map_subscribe_transient_local: true
        subscribe_to_updates: true

      projected_static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /projected_map
        map_subscribe_transient_local: true
        subscribe_to_updates: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 1.2

      local_obstacle_layer:
        plugin: "costmap_intensity::ObstacleLayerIntensity"
        enabled: true
        combination_method: 1
        clear_on_update: false
        footprint_clearing_enabled: true
        max_obstacle_intensity: 2.0
        min_obstacle_intensity: 0.3
        robot_origin_fallback_enabled: false
        robot_origin_fallback_distance: 1.0
        observation_sources: pointcloud
        pointcloud:
          topic: /gen0_mapping/terrain_map
          observation_persistence: 0.0
          expected_update_rate: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: -2.0
          obstacle_max_range: 7.0
          obstacle_min_range: 0.15
          raytrace_max_range: 8.0
          raytrace_min_range: 0.1
          clearing: true
          marking: true
          data_type: "PointCloud2"

      actor_obstacle_layer:
        plugin: "costmap_intensity::ObstacleLayerIntensity"
        enabled: true
        combination_method: 1
        clear_on_update: true
        footprint_clearing_enabled: false
        max_obstacle_intensity: 2.0
        min_obstacle_intensity: 0.3
        robot_origin_fallback_enabled: true
        robot_origin_fallback_distance: 1.0
        observation_sources: actors
        actors:
          topic: /gen0_mapping/actor_obstacles
          observation_persistence: 0.0
          expected_update_rate: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: -2.0
          obstacle_max_range: 14.0
          obstacle_min_range: 0.15
          raytrace_max_range: 15.0
          raytrace_min_range: 0.1
          clearing: true
          marking: true
          data_type: "PointCloud2"

      always_send_full_costmap: true
