#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 <rosbridge-public-hostname> [web_control_directory]" >&2
  echo "Example: $0 ros.sweeper.example.com" >&2
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage
  exit 2
fi

rosbridge_host="$1"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd -- "${script_dir}/../.." && pwd)"
web_directory="${2:-${repository_root}/web_control}"
runtime_file="${web_directory}/runtime-config.js"

if [[ ! "${rosbridge_host}" =~ ^[A-Za-z0-9.-]+$ ]]; then
  echo "Invalid hostname: ${rosbridge_host}" >&2
  exit 2
fi

if [[ ! -d "${web_directory}" ]]; then
  echo "Web directory does not exist: ${web_directory}" >&2
  exit 1
fi

printf '%s\n' \
  '// Generated by deploy/cloudflare/configure_web.sh. Contains no secret.' \
  'window.GEN0_WEB_CONFIG = {' \
  "  rosbridgeUrl: \"wss://${rosbridge_host}\"," \
  '  autoConnect: true,' \
  '};' > "${runtime_file}"

echo "Configured ${runtime_file} to use wss://${rosbridge_host}"
